"""
Field descriptions for Shipment DocType.
Stored here for backend/AI reference. Maps field names to their IATA DE codes and descriptions.
"""

FIELD_DESCRIPTIONS = {
    "airline_prefix": "DE112 - drives AWB number",
    "awb_serial_number": "DE113 (8 digits, mod-7 check)",
    "origin": "DE313",
    "destination": "DE313",
    "shipment_description_code": "DE703 (T=Total, P=Part)",
    "number_of_pieces": "DE701",
    "weight_code": "DE601",
    "weight": "DE600",
    "volume_code": "DE604",
    "volume_amount": "DE500",
    "density_indicator": "DE603",
    "density_group": "DE602",
    "currency": "DE606",
    "charge_code": "DE503",
    "wt_val_prepaid_collect": "DE403",
    "other_charges_prepaid_collect": "DE403",
    "declared_value_carriage_type": "DE510",
    "declared_value_customs_type": "DE509",
    "insurance_type": "DE508",
    "cc_dest_currency": "DE606",
    "rate_of_exchange": "DE607",
    "cc_charges_dest": "DE501",
    "charges_at_dest": "DE501",
    "total_collect_charges": "DE501",
    "shippers_certification_signature": "CER / DE414",
    "issue_date": "ISU / DE200-202",
    "issue_place": "ISU / DE302",
    "carrier_execution_signature": "ISU / DE414",
    "sender_file_reference": "REF / DE117",
    "sender_office_address": "REF / DE313+107+308",
    "sender_participant_id": "REF / DE319",
    "sender_participant_code": "REF / DE320",
    "customs_origin_code": "COR / DE906",
    "nominated_handling_name": "NOM / DE300",
    "nominated_handling_place": "NOM / DE302",
    "no_commission_indicator": "COI / DE614",
    "commission_amount": "COI / DE613",
    "commission_percentage": "COI / DE613",
    "sales_incentive_amount": "SII / DE501",
    "sales_incentive_indicator": "SII / DE614",
    "agent_reference": "ARD / DE117",
}
